#!/usr/bin/env node

import minimist from 'minimist';
import Swagger from './swagger';

const argv = minimist(process.argv.slice(4));

const swagger = new Swagger(process.argv[2]);
swagger.generateAndWrite(process.argv[3], argv);
